"""
predict.py — Trained model ko use karke naye SAST findings pe prediction lena

Real project me: ye logic FastAPI microservice ke andar hai (service.py dekho),
jise aapka Node.js backend REST call karega har scan ke baad.

Run: python3 predict.py
"""

import os
import json
import joblib
import pandas as pd

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
model = joblib.load(os.path.join(BASE_DIR, "model.joblib"))
rule_encoder = joblib.load(os.path.join(BASE_DIR, "rule_encoder.joblib"))
cwe_encoder = joblib.load(os.path.join(BASE_DIR, "cwe_encoder.joblib"))

# ─── Conformal Threshold Loading ──────────────────────────────────────────────
THRESHOLDS_PATH = os.path.join(BASE_DIR, "thresholds.json")
FIXED_THRESHOLD = 0.4  # Legacy fallback threshold

if os.path.exists(THRESHOLDS_PATH):
    with open(THRESHOLDS_PATH, "r", encoding="utf-8") as _f:
        _thresholds_data = json.load(_f)
    CONFORMAL_DEFAULT = _thresholds_data.get("default", FIXED_THRESHOLD)
    CONFORMAL_PER_CWE = _thresholds_data.get("per_cwe", {})
    USE_CONFORMAL = True
    print(f"[predict] Conformal thresholds loaded: default={CONFORMAL_DEFAULT}, {len(CONFORMAL_PER_CWE)} CWE-specific thresholds")
else:
    CONFORMAL_DEFAULT = FIXED_THRESHOLD
    CONFORMAL_PER_CWE = {}
    USE_CONFORMAL = False
    print(f"[predict] No thresholds.json found, using fixed threshold={FIXED_THRESHOLD}")


def get_threshold_for_cwe(cwe_id: str) -> float:
    """
    Per-CWE conformal threshold return karta hai.
    Agar conformal calibration available nahi hai ya CWE unseen hai,
    toh appropriate fallback threshold use hota hai.
    """
    if not USE_CONFORMAL:
        return FIXED_THRESHOLD
    return CONFORMAL_PER_CWE.get(cwe_id, CONFORMAL_DEFAULT)


# NOTE: ye list generate_sample_data.py / train.py ke feature_cols se exactly match honi chahiye
feature_cols = [
    "rule_id_enc", "cwe_id_enc", "is_string_concat", "is_parameterized_query",
    "has_sanitizer_nearby", "in_test_file", "is_in_vendor_or_generated_dir",
    "taint_source_distance", "function_complexity", "code_snippet_length",
    "variable_name_entropy", "is_user_input_direct", "has_type_validation",
    "is_third_party_lib_call", "same_finding_seen_before_count",
    "developer_dismissed_similar_before", "file_change_frequency",
    "is_authenticated_endpoint",
]

# Unseen rule_id/cwe_id encoder me na ho to crash na ho, isliye safe fallback
def safe_encode(encoder, value):
    try:
        return encoder.transform([value])[0]
    except ValueError:
        return -1  # unknown category ke liye fallback code


def explain_prediction(finding: dict, prediction: str) -> list[str]:
    reasons = []
    if prediction == "FALSE_POSITIVE":
        if finding.get("is_parameterized_query") == 1:
            reasons.append("Parameterized query detected (places inputs in placeholders instead of direct string interpolation)")
        if finding.get("has_sanitizer_nearby") == 1:
            reasons.append("Sanitization function/escape utility detected in close proximity to the sink")
        if finding.get("in_test_file") == 1:
            reasons.append("File located inside a testing or mock directory (Low production threat vector)")
        if finding.get("is_in_vendor_or_generated_dir") == 1:
            reasons.append("File is located inside vendor, node_modules, or autogenerated directories")
        if finding.get("has_type_validation") == 1:
            reasons.append("Input variables pass through explicit type check or schema validation (e.g. Zod, Joi)")
        if finding.get("taint_source_distance", 5) > 10:
            reasons.append(f"Taint source-to-sink distance is long ({finding.get('taint_source_distance')} nodes), indicating low likelihood of direct user control")
        if finding.get("developer_dismissed_similar_before") == 1:
            reasons.append("Developer has historically dismissed similar SAST findings on this rule in this repository")
        if finding.get("is_user_input_direct") == 0:
            reasons.append("Input source is not directly bounded to HTTP request parameters")
        if not reasons:
            reasons.append("Model combined multiple structural features to determine a low overall exploit probability")
    else:
        if finding.get("is_string_concat") == 1:
            reasons.append("Direct string concatenation/interpolation detected on a sensitive execution sink")
        if finding.get("is_user_input_direct") == 1:
            reasons.append("Untrusted HTTP request input flows directly to the sink without validation")
        if finding.get("is_parameterized_query") == 0 and "sqli" in finding.get("rule_id", "").lower():
            reasons.append("SQL query lacks parameterization (High risk of SQL injection)")
        if finding.get("has_sanitizer_nearby") == 0:
            reasons.append("No sanitization check or input filter found nearby in the syntax scope")
        if finding.get("taint_source_distance", 5) <= 3:
            reasons.append(f"Extremely short taint source-to-sink distance ({finding.get('taint_source_distance')} nodes) -- user input reaches execution directly")
        if finding.get("in_test_file") == 0 and finding.get("is_in_vendor_or_generated_dir") == 0:
            reasons.append("Finding resides in active production source code path")
        if not reasons:
            reasons.append("Model calculated a high risk pattern match against known vulnerable code templates")
    return reasons


def predict_finding(finding: dict, include_explanation: bool = False) -> dict:
    """
    finding: SAST scan se aaya raw finding (dict), jisme upar wale saare
    feature_cols (rule_id, cwe_id ke alawa) ke raw values hone chahiye.

    Uses per-CWE conformal threshold when available (USE_CONFORMAL=True),
    falls back to fixed 0.4 threshold otherwise.
    """
    row = finding.copy()
    row["rule_id_enc"] = safe_encode(rule_encoder, row["rule_id"])
    row["cwe_id_enc"] = safe_encode(cwe_encoder, row["cwe_id"])

    X = pd.DataFrame([row])[feature_cols]
    proba = model.predict_proba(X)[0][1]  # probability of being REAL

    # Conformal per-CWE threshold (or fixed fallback)
    cwe_id = finding.get("cwe_id", "")
    threshold = get_threshold_for_cwe(cwe_id)

    label = "REAL" if proba >= threshold else "FALSE_POSITIVE"

    explanations = explain_prediction(finding, label)

    res = {
        "prediction": label,
        "confidence": round(float(proba), 3),
        "threshold_used": round(threshold, 4),
        "conformal_calibrated": USE_CONFORMAL,
        "explanations": explanations
    }

    if include_explanation:
        try:
            from explainer import explain_prediction_shap
            res["explanation"] = explain_prediction_shap(X)
        except Exception as e:
            res["explanation"] = [{"error": f"Failed to compute SHAP: {str(e)}"}]

    return res


if __name__ == "__main__":
    # Example 1: likely REAL vulnerability
    example_1 = {
        "rule_id": "sqli-concat", "cwe_id": "CWE-89",
        "is_string_concat": 1, "is_parameterized_query": 0,
        "has_sanitizer_nearby": 0, "in_test_file": 0,
        "is_in_vendor_or_generated_dir": 0, "taint_source_distance": 2,
        "function_complexity": 14, "code_snippet_length": 90,
        "variable_name_entropy": 2.0, "is_user_input_direct": 1,
        "has_type_validation": 0, "is_third_party_lib_call": 0,
        "same_finding_seen_before_count": 1, "developer_dismissed_similar_before": 0,
        "file_change_frequency": 22, "is_authenticated_endpoint": 0,
    }

    # Example 2: likely FALSE POSITIVE
    example_2 = {
        "rule_id": "sqli-concat", "cwe_id": "CWE-89",
        "is_string_concat": 0, "is_parameterized_query": 1,
        "has_sanitizer_nearby": 1, "in_test_file": 1,
        "is_in_vendor_or_generated_dir": 0, "taint_source_distance": 15,
        "function_complexity": 3, "code_snippet_length": 40,
        "variable_name_entropy": 2.5, "is_user_input_direct": 0,
        "has_type_validation": 1, "is_third_party_lib_call": 1,
        "same_finding_seen_before_count": 8, "developer_dismissed_similar_before": 1,
        "file_change_frequency": 2, "is_authenticated_endpoint": 1,
    }

    print("Example 1 (expected REAL):", predict_finding(example_1))
    print("Example 2 (expected FALSE_POSITIVE):", predict_finding(example_2))
